
package de.crowdcode.jaxws.client.stub;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://crowdcode.de/jaxws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param dividend
     * @param divisor
     * @return
     *     returns java.lang.Double
     * @throws CalculatorException_Exception
     */
    @WebMethod(action = "urn:divideNumbers")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://crowdcode.de/jaxws", className = "de.crowdcode.jaxws.client.stub.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://crowdcode.de/jaxws", className = "de.crowdcode.jaxws.client.stub.DivideResponse")
    @Action(input = "urn:divideNumbers", output = "http://crowdcode.de/jaxws/Calculator/divideResponse", fault = {
        @FaultAction(className = CalculatorException_Exception.class, value = "http://crowdcode.de/jaxws/Calculator/divide/Fault/CalculatorException")
    })
    public Double divide(
        @WebParam(name = "dividend", targetNamespace = "")
        Double dividend,
        @WebParam(name = "divisor", targetNamespace = "")
        Double divisor)
        throws CalculatorException_Exception
    ;

    /**
     * 
     * @param value
     * @return
     *     returns java.lang.Integer
     * @throws CalculatorException_Exception
     */
    @WebMethod(action = "urn:sumNumbers")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sum", targetNamespace = "http://crowdcode.de/jaxws", className = "de.crowdcode.jaxws.client.stub.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://crowdcode.de/jaxws", className = "de.crowdcode.jaxws.client.stub.SumResponse")
    @Action(input = "urn:sumNumbers", output = "http://crowdcode.de/jaxws/Calculator/sumResponse", fault = {
        @FaultAction(className = CalculatorException_Exception.class, value = "http://crowdcode.de/jaxws/Calculator/sum/Fault/CalculatorException")
    })
    public Integer sum(
        @WebParam(name = "value", targetNamespace = "")
        List<Integer> value)
        throws CalculatorException_Exception
    ;

}
